# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrinkingBruh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for DrinkingBruh
  pod 'Firebase/Core'  
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  # UI
  pod 'SideMenu'
  pod 'SkyFloatingLabelTextField', '~> 2.0.0'
 # Google Maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  target 'DrinkingBruhTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrinkingBruhUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
